em0nti/project-amenic-6

src/partials/card.html
src/sass/components/_card.scss

add 1 class to card and CSS for it

minor update

---

src/partials/catalog-list.html
src/sass/components/_catalog-list.scss

1) Убрал отступы
2) Переименовал классы по БЕМ

Corrected errors in catalog-list (Novikov)

---

src/partials/weekly-trends.html
src/sass/components/_weekly-trends.scss

1) Удалил со стилей movi-card-general-set так как его добавили в стили карточки Антон. 2) Исправил название класса по БЕМ.
Остальное как мне кажется не стоит трогать. Там сделана шапка с названием и ссылкой + список карт.

Corrected weekly-trends (Novikov)

---

src/partials/card.html
src/sass/components/_card.scss

добавил более плавный переход градиента и увеличил верхний паддинг футера карточки так чтобы названия фильмов в несколько строк нормально отображались

card footer gradient fix

---

src/js/api_markup_service.js
src/js/constants.js
src/js/index.js
src/partials/upcoming-this-month.html
src/partials/weekly-trends.html

Make render weekly trends for main page and base render for film upcoming

Timur render js 2

---

src/partials/library-list.html
src/sass/components/_library-list.scss

Исправил стили и добавил класс card-set

library-list-correct-style

---

src/js/api_markup_service.js

import rating.js apimarkupservice

import rating,js in apimarkupservice

---

src/index.html
src/sass/components/hero/_hero-home.scss
src/sass/components/hero/_hero-library.scss
src/sass/components/hero/_hero-start.scss

виправив медіа і вирівняв контейнер

newGoodHero

---

src/js/modals/init-modals.js
src/js/watch-trailer.js

додав передачу ID фільму при натисканні кнопки.
функція приймає ID і показує потрібний трейлер

ID in button

---

src/index.html
src/js/api_markup_service.js
src/js/index.js

fix package json and lock file

fix weekly trends markup upcoming fix index.js

---

src/js/rating.js
src/sass/components/_card.scss
src/sass/components/_rating-stars.scss
src/sass/index.scss

костиль через інлайн, але працює. треба прибрати display: none; як я писав у слак щоб футер картки у weekly trends відображався

stars done

---

src/sass/components/hero/_hero-start.scss

remove-stile

---

src/js/catalog.js
src/js/index.js
src/js/library.js
src/js/show-current-page.js

1) Коли Поліна внесе зміни у хедер (додасть класи home, catalog, library) функція буде працювати. Поліні  я сказав.

show kurrent page

---

src/js/rating.js
src/sass/components/_card.scss

тепер функція рендеру зірочок очикує другим елементом строку "hero" або "card". в залежності від переданного елементу виконується потрібний рендер

fixed starrating for hero

---

src/js/index.js

onChangeWeeklyTrendsByResizeViewport
onChangeWeeklyTrendsByScreenWidth

async functions index js

---

src/js/api_fetch_service.js
src/js/api_markup_service.js
src/js/constants.js
src/js/index.js

Timur branch 09.05.2023#7 

---

src/js/constants.js
src/partials/hero-start.html

fix ID Get Started Button

---

src/sass/components/_modal-popup.scss
src/sass/components/_upcoming-this-month.scss
src/sass/components/_weekly-trends.scss
src/sass/utils/_variable.scss

прийми це частина готово, інше роблю

remov-color

---

src/partials/not-found-film-catalog.html
src/partials/not-found-film-library.html
src/sass/components/_not-found-film.scss
src/sass/index.scss

Там в каталоге и библиотеки немного разные надписи. Потому посылаю сразу две разметки и к ним один файл стилей.

catalog-library-not-found-message

---

src/sass/components/_card.scss

Animated cards

---

src/sass/components/buttons/_button-add.scss
src/sass/components/buttons/_button-main.scss
src/sass/components/buttons/_button-search.scss
src/sass/utils/_variable.scss

fixed buttons colors to switcher
Змінював налаштування в root, але під свої налаштування робив окремі змінні, Віктора змінні не чіпав

fixed buttons

---

src/partials/modal-popup.html
src/partials/not-found-film-popup.html
src/sass/components/_not-found-film.scss

OPPS-popup

---

src/sass/components/buttons/_button-search.scss

На кнопку поиска стоял фокус, потому она оставалась белой. Я оставил только ховер.

search button (catalog)

---

src/partials/not-found-film-library.html
src/sass/components/_not-found-film-library.scss

Поменял кнопку на ссылку. Если ее генерить динамически в случае отсутствия фильмов, тогда ничего больше придумывать не нужно.

fixed button on library

---

src/js/catalog-new.js

исправлен баг при котором страница скролится автоматически вверх после выполнения поиска фильмов

page not jumping after search anymore

---

src/js/api_tmdb/api_fetch-by-query.js
src/js/catalog-new.js
src/js/components/render-search-fail.js
src/js/components/search-fail-markup.js

при пустом запросе и при неправильном запросе добавляется секция с сообщением

search fail done

---

src/js/catalog-new.js

починил рендеринг трендовых фильмов

weekly trends fixed
